Models/Cesta.cs
using FeiraDoPedro.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FeiraDoPedro

{
    public class Cesta
    {
        public int Id { get; set; }
        public int IdProduto { get; set; }
        public List<Produto> Produtos { get; set; }
        public double PrecoTotal { get; set; }
        public int NumeroUnico { get; set; }
        public float Quantidade { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace FeiraDoPedro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FeiraDoPedro.Models
{
    public class Produto 
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe o nome do produto!")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o preço do produto!")]
        [Display(Name = "Preço")]
        public double Preco { get; set; }

        [Required(ErrorMessage = "Insira a imagem do produto")]
        [Display(Name = "Foto")]
        public string Foto { get; set; }
        //public int CestaId { get; set; }
        public Cesta Cesta { get; set; }


    }
}

Controllers/CestaController.cs
using FeiraDoPedro.Models;
using FeiraDoPedro.Service;
using FeiraDoPedro.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FeiraDoPedro.Controllers
{
    public class CestaController : Controller
    {
        IProdutoService _produtoService;
        ICestaService _cestaService;
        public CestaController(IProdutoService produtoService, ICestaService cestaService)
        {
            _produtoService = produtoService;
            _cestaService = cestaService;
        }

        [HttpPost]
        public IActionResult AdicionarItem(int Id)
        {
            var produto = _produtoService.get(Id);
            var cesta = _cestaService.get(1);
            cesta.Produtos.Add(produto);
            _cestaService.update(cesta);
            return View();
        }

        [HttpDelete]
        public IActionResult RemoverItem(int Id)
        {
            var produto = _produtoService.get(Id);
            var cesta = _cestaService.get(1);
            cesta.Produtos.Remove(produto);
            _cestaService.update(cesta);
            return View();
        }


        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cesta cesta)
        {
            if (!ModelState.IsValid) return View();

            return _cestaService.create(cesta) ?
                RedirectToAction(nameof(Index)) :
                View();
        }
    }
}

Controllers/HomeController.cs
using FeiraDoPedro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FeiraDoPedro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutoController.cs
using FeiraDoPedro.Models;
using FeiraDoPedro.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FeiraDoPedro.Controllers
{
    //Controllers são responsáveis por trabalhar e buscar dados que serão utilizados para o usuário.
    public class ProdutoController : Controller
    {
        IProdutoService _produtoService; 
        
        public ProdutoController(IProdutoService produtoService)
        {            
            _produtoService = produtoService;
        }

        public IActionResult Index()
        {
            return View(_produtoService.getAll());
        }


        [HttpGet]        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Produto produto)
        {
            if (!ModelState.IsValid) return View(produto);

            return _produtoService.create(produto) ?
                RedirectToAction(nameof(Index)) :
                View(produto);
        }


        public IActionResult Read(int? id) // localhost/Veiculo/Read/id?
        {
            Produto produto = _produtoService.get(id);
            return produto != null ?
                View(produto) :
                NotFound();
        }

        [HttpGet]
        [Authorize]
        public IActionResult Update(int? id)
        {
            var veiculo = _produtoService.get(id);
            return veiculo != null ? 
                View(veiculo) :                
                NotFound(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Produto produto)
        {
            if (!ModelState.IsValid) return View(produto);
            
            if (_produtoService.update(produto)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(produto);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (_produtoService.delete(id)) 
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Views/Cesta/ResumoCesta.cshtml
@*@model List<Cesta>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<h2>Produtos do Feirante</h2>
@if (SignInManager.IsSignedIn(User))
{
    <a class="btn btn-link" asp-controller="Produto" asp-action="Create">Cadastrar novo produto!</a>
}

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.First().Id)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().Produto)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().Quantidade)</th>
            <th style="margin-left: auto; margin-right: auto; text-align: center;">@Html.DisplayNameFor(Model => Model.First().Foto)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Produto p in Model){
                        
            <tr class="">
                <td> @Html.DisplayFor(Model => item.Id) </td>
                <td> @Html.DisplayFor(Model => item.Nome) </td>
                <td> @Html.DisplayFor(Model => item.Preco) </td>                
                <td> <img src="@Html.DisplayFor(Model => item.Foto)</td>                
                <td>
                    <a asp-controller="Cesta" asp-action="Add" asp-route-id="@cesta.Id">Finalizar compra</a>                   
                 </td>
            </tr>
        }
    </tbody>
</table>
<br>


<a class="btn btn-info" asp-controller="Cesta" asp-action="Index">Finalizar compra!</a>*@

Views/Home/Index.cshtml
@*@{
    ViewData["Title"] = "Home Page";
}


<div class="form-group">

    <a class="btn btn-info" asp-controller="Veiculo" asp-action="Index">Veiculos</a>
    <a class="btn btn-info" asp-controller="Vendedor" asp-action="Index">Vendedores</a>

</div>*@

Views/Produto/Create.cshtml
@model Produto


<div class="row">
    <form class="col-md-4" asp-action="Create">
        <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span class="text-danger" asp-validation-for="Nome"></span>
        </div>
        <div class="form-group">
            <label asp-for="Preco" class="control-label"></label>
            <input asp-for="Preco" class="form-control" />
            <span class="text-danger" asp-validation-for="Preco"></span>
        </div>      
        <div class="form-group">
            <label asp-for="Foto" class="control-label"></label>
            <input asp-for="Foto" class="form-control" />
            <span class="text-danger" asp-validation-for="Foto"></span>
        </div>
        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Criar!" />
            <a class="btn btn-info" asp-controller="Produto" asp-action="Index">Voltar!</a>
        </div>
    </form>
</div>

Views/Produto/Index.cshtml
@model List<Produto>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<h2>Produtos do Feirante</h2>
@if (SignInManager.IsSignedIn(User))
{
    <a class="btn btn-link" asp-controller="Produto" asp-action="Create">Cadastrar novo produto!</a>
}

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.First().Id)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().Nome)</th>
            <th>@Html.DisplayNameFor(Model => Model.First().Preco)</th>
            <th style="text-align: center">@Html.DisplayNameFor(Model => Model.First().Foto)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Produto produto in Model){
                        
            <tr class="">
                <td> @Html.DisplayFor(Model => produto.Id) </td>
                <td> @Html.DisplayFor(Model => produto.Nome) </td>
                <td> @Html.DisplayFor(Model => produto.Preco) </td>                
                <td> <img src="@Html.DisplayFor(Model => produto.Foto)" alt="" width="auto" height="100px" /> </td>                
                <td>
                    <a asp-controller="Cesta" asp-action="Update" asp-route-id="@produto.Id">Adicionar Item na Cesta</a> |                    
                    <a asp-controller="Cesta" asp-action="Delete" asp-route-id="@produto.Id">Remover Item da Cesta</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<br>


<a class="btn btn-info" asp-controller="Home" asp-action="Index">Voltar!</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Feira do Pedro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FeiraDoPedro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cesta" asp-action="Index">Cesta</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Feira do Pedro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>